openmpi/3.1.4-opa10.10(5):ERROR:151: Module 'openmpi/3.1.4-opa10.10' depends on one of the module(s) 'nvhpc/22.2 nvhpc/21.7 nvhpc/21.3 nvhpc/21.2 nvhpc/20.9'
openmpi/3.1.4-opa10.10(5):ERROR:102: Tcl command execution failed: prereq cuda nvhpc

Requirement already satisfied: pip in /home/7/21D30114/.local/lib/python3.7/site-packages (23.0.1)
Requirement already satisfied: laspy in /home/7/21D30114/.local/lib/python3.7/site-packages (2.4.1)
Requirement already satisfied: numpy in /home/7/21D30114/.local/lib/python3.7/site-packages (from laspy) (1.21.6)
Requirement already satisfied: matplotlib in /home/7/21D30114/.local/lib/python3.7/site-packages (3.5.3)
Requirement already satisfied: pillow>=6.2.0 in /home/7/21D30114/.local/lib/python3.7/site-packages (from matplotlib) (9.4.0)
Requirement already satisfied: pyparsing>=2.2.1 in /home/7/21D30114/.local/lib/python3.7/site-packages (from matplotlib) (3.0.9)
Requirement already satisfied: fonttools>=4.22.0 in /home/7/21D30114/.local/lib/python3.7/site-packages (from matplotlib) (4.38.0)
Requirement already satisfied: cycler>=0.10 in /home/7/21D30114/.local/lib/python3.7/site-packages (from matplotlib) (0.11.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /home/7/21D30114/.local/lib/python3.7/site-packages (from matplotlib) (1.4.4)
Requirement already satisfied: python-dateutil>=2.7 in /home/7/21D30114/.local/lib/python3.7/site-packages (from matplotlib) (2.8.2)
Requirement already satisfied: numpy>=1.17 in /home/7/21D30114/.local/lib/python3.7/site-packages (from matplotlib) (1.21.6)
Requirement already satisfied: packaging>=20.0 in /home/7/21D30114/.local/lib/python3.7/site-packages (from matplotlib) (23.0)
Requirement already satisfied: typing-extensions in /home/7/21D30114/.local/lib/python3.7/site-packages (from kiwisolver>=1.0.1->matplotlib) (4.5.0)
Requirement already satisfied: six>=1.5 in /home/7/21D30114/.local/lib/python3.7/site-packages (from python-dateutil>=2.7->matplotlib) (1.16.0)
Requirement already satisfied: gym in /home/7/21D30114/.local/lib/python3.7/site-packages (0.26.2)
Requirement already satisfied: gym-notices>=0.0.4 in /home/7/21D30114/.local/lib/python3.7/site-packages (from gym) (0.0.8)
Requirement already satisfied: numpy>=1.18.0 in /home/7/21D30114/.local/lib/python3.7/site-packages (from gym) (1.21.6)
Requirement already satisfied: importlib-metadata>=4.8.0 in /home/7/21D30114/.local/lib/python3.7/site-packages (from gym) (6.0.0)
Requirement already satisfied: cloudpickle>=1.2.0 in /home/7/21D30114/.local/lib/python3.7/site-packages (from gym) (2.2.1)
Requirement already satisfied: typing-extensions>=3.6.4 in /home/7/21D30114/.local/lib/python3.7/site-packages (from importlib-metadata>=4.8.0->gym) (4.5.0)
Requirement already satisfied: zipp>=0.5 in /home/7/21D30114/.local/lib/python3.7/site-packages (from importlib-metadata>=4.8.0->gym) (3.15.0)
Requirement already satisfied: keras in /home/7/21D30114/.local/lib/python3.7/site-packages (2.11.0)
Requirement already satisfied: keras_preprocessing in /home/7/21D30114/.local/lib/python3.7/site-packages (1.1.2)
Requirement already satisfied: six>=1.9.0 in /home/7/21D30114/.local/lib/python3.7/site-packages (from keras_preprocessing) (1.16.0)
Requirement already satisfied: numpy>=1.9.1 in /home/7/21D30114/.local/lib/python3.7/site-packages (from keras_preprocessing) (1.21.6)
Requirement already satisfied: opencv-python in /home/7/21D30114/.local/lib/python3.7/site-packages (4.7.0.72)
Requirement already satisfied: numpy>=1.17.0 in /home/7/21D30114/.local/lib/python3.7/site-packages (from opencv-python) (1.21.6)
Requirement already satisfied: packaging in /home/7/21D30114/.local/lib/python3.7/site-packages (23.0)
Requirement already satisfied: tensorflow_probability in /home/7/21D30114/.local/lib/python3.7/site-packages (0.19.0)
Requirement already satisfied: cloudpickle>=1.3 in /home/7/21D30114/.local/lib/python3.7/site-packages (from tensorflow_probability) (2.2.1)
Requirement already satisfied: numpy>=1.13.3 in /home/7/21D30114/.local/lib/python3.7/site-packages (from tensorflow_probability) (1.21.6)
Requirement already satisfied: gast>=0.3.2 in /home/7/21D30114/.local/lib/python3.7/site-packages (from tensorflow_probability) (0.5.3)
Requirement already satisfied: six>=1.10.0 in /home/7/21D30114/.local/lib/python3.7/site-packages (from tensorflow_probability) (1.16.0)
Requirement already satisfied: decorator in /home/7/21D30114/.local/lib/python3.7/site-packages (from tensorflow_probability) (5.1.1)
Requirement already satisfied: dm-tree in /home/7/21D30114/.local/lib/python3.7/site-packages (from tensorflow_probability) (0.1.8)
Requirement already satisfied: absl-py in /home/7/21D30114/.local/lib/python3.7/site-packages (from tensorflow_probability) (1.4.0)
Requirement already satisfied: scikit-image in /home/7/21D30114/.local/lib/python3.7/site-packages (0.19.3)
Requirement already satisfied: networkx>=2.2 in /home/7/21D30114/.local/lib/python3.7/site-packages (from scikit-image) (2.6.3)
Requirement already satisfied: imageio>=2.4.1 in /home/7/21D30114/.local/lib/python3.7/site-packages (from scikit-image) (2.26.0)
Requirement already satisfied: numpy>=1.17.0 in /home/7/21D30114/.local/lib/python3.7/site-packages (from scikit-image) (1.21.6)
Requirement already satisfied: PyWavelets>=1.1.1 in /home/7/21D30114/.local/lib/python3.7/site-packages (from scikit-image) (1.3.0)
Requirement already satisfied: pillow!=7.1.0,!=7.1.1,!=8.3.0,>=6.1.0 in /home/7/21D30114/.local/lib/python3.7/site-packages (from scikit-image) (9.4.0)
Requirement already satisfied: scipy>=1.4.1 in /home/7/21D30114/.local/lib/python3.7/site-packages (from scikit-image) (1.7.3)
Requirement already satisfied: packaging>=20.0 in /home/7/21D30114/.local/lib/python3.7/site-packages (from scikit-image) (23.0)
Requirement already satisfied: tifffile>=2019.7.26 in /home/7/21D30114/.local/lib/python3.7/site-packages (from scikit-image) (2021.11.2)
Requirement already satisfied: pybullet in /home/7/21D30114/.local/lib/python3.7/site-packages (3.2.5)
Requirement already satisfied: ray[rllib]==2.3 in /home/7/21D30114/.local/lib/python3.7/site-packages (2.3.0)
Requirement already satisfied: jsonschema in /home/7/21D30114/.local/lib/python3.7/site-packages (from ray[rllib]==2.3) (4.17.3)
Requirement already satisfied: frozenlist in /home/7/21D30114/.local/lib/python3.7/site-packages (from ray[rllib]==2.3) (1.3.3)
Requirement already satisfied: protobuf!=3.19.5,>=3.15.3 in /home/7/21D30114/.local/lib/python3.7/site-packages (from ray[rllib]==2.3) (3.20.3)
Requirement already satisfied: attrs in /home/7/21D30114/.local/lib/python3.7/site-packages (from ray[rllib]==2.3) (22.2.0)
Requirement already satisfied: aiosignal in /home/7/21D30114/.local/lib/python3.7/site-packages (from ray[rllib]==2.3) (1.3.1)
Requirement already satisfied: click>=7.0 in /home/7/21D30114/.local/lib/python3.7/site-packages (from ray[rllib]==2.3) (8.1.3)
Requirement already satisfied: pyyaml in /home/7/21D30114/.local/lib/python3.7/site-packages (from ray[rllib]==2.3) (6.0)
Requirement already satisfied: grpcio>=1.32.0 in /home/7/21D30114/.local/lib/python3.7/site-packages (from ray[rllib]==2.3) (1.51.3)
Requirement already satisfied: requests in /home/7/21D30114/.local/lib/python3.7/site-packages (from ray[rllib]==2.3) (2.28.2)
Requirement already satisfied: typing-extensions in /home/7/21D30114/.local/lib/python3.7/site-packages (from ray[rllib]==2.3) (4.5.0)
Requirement already satisfied: numpy>=1.16 in /home/7/21D30114/.local/lib/python3.7/site-packages (from ray[rllib]==2.3) (1.21.6)
Requirement already satisfied: filelock in /home/7/21D30114/.local/lib/python3.7/site-packages (from ray[rllib]==2.3) (3.10.0)
Requirement already satisfied: msgpack<2.0.0,>=1.0.0 in /home/7/21D30114/.local/lib/python3.7/site-packages (from ray[rllib]==2.3) (1.0.5)
Requirement already satisfied: virtualenv>=20.0.24 in /home/7/21D30114/.local/lib/python3.7/site-packages (from ray[rllib]==2.3) (20.21.0)
Requirement already satisfied: gymnasium==0.26.3 in /home/7/21D30114/.local/lib/python3.7/site-packages (from ray[rllib]==2.3) (0.26.3)
Requirement already satisfied: scikit-image in /home/7/21D30114/.local/lib/python3.7/site-packages (from ray[rllib]==2.3) (0.19.3)
Requirement already satisfied: dm-tree in /home/7/21D30114/.local/lib/python3.7/site-packages (from ray[rllib]==2.3) (0.1.8)
Requirement already satisfied: lz4 in /home/7/21D30114/.local/lib/python3.7/site-packages (from ray[rllib]==2.3) (4.3.2)
Requirement already satisfied: tensorboardX>=1.9 in /home/7/21D30114/.local/lib/python3.7/site-packages (from ray[rllib]==2.3) (2.6)
Requirement already satisfied: tabulate in /home/7/21D30114/.local/lib/python3.7/site-packages (from ray[rllib]==2.3) (0.9.0)
Requirement already satisfied: scipy in /home/7/21D30114/.local/lib/python3.7/site-packages (from ray[rllib]==2.3) (1.7.3)
Requirement already satisfied: typer in /home/7/21D30114/.local/lib/python3.7/site-packages (from ray[rllib]==2.3) (0.7.0)
Requirement already satisfied: pandas in /home/7/21D30114/.local/lib/python3.7/site-packages (from ray[rllib]==2.3) (1.3.5)
Requirement already satisfied: rich in /home/7/21D30114/.local/lib/python3.7/site-packages (from ray[rllib]==2.3) (13.3.2)
Requirement already satisfied: importlib-metadata>=4.8.0 in /home/7/21D30114/.local/lib/python3.7/site-packages (from gymnasium==0.26.3->ray[rllib]==2.3) (6.0.0)
Requirement already satisfied: gymnasium-notices>=0.0.1 in /home/7/21D30114/.local/lib/python3.7/site-packages (from gymnasium==0.26.3->ray[rllib]==2.3) (0.0.1)
Requirement already satisfied: cloudpickle>=1.2.0 in /home/7/21D30114/.local/lib/python3.7/site-packages (from gymnasium==0.26.3->ray[rllib]==2.3) (2.2.1)
Requirement already satisfied: packaging in /home/7/21D30114/.local/lib/python3.7/site-packages (from tensorboardX>=1.9->ray[rllib]==2.3) (23.0)
Requirement already satisfied: platformdirs<4,>=2.4 in /home/7/21D30114/.local/lib/python3.7/site-packages (from virtualenv>=20.0.24->ray[rllib]==2.3) (3.1.1)
Requirement already satisfied: distlib<1,>=0.3.6 in /home/7/21D30114/.local/lib/python3.7/site-packages (from virtualenv>=20.0.24->ray[rllib]==2.3) (0.3.6)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in /home/7/21D30114/.local/lib/python3.7/site-packages (from jsonschema->ray[rllib]==2.3) (0.19.3)
Requirement already satisfied: importlib-resources>=1.4.0 in /home/7/21D30114/.local/lib/python3.7/site-packages (from jsonschema->ray[rllib]==2.3) (5.12.0)
Requirement already satisfied: pkgutil-resolve-name>=1.3.10 in /home/7/21D30114/.local/lib/python3.7/site-packages (from jsonschema->ray[rllib]==2.3) (1.3.10)
Requirement already satisfied: python-dateutil>=2.7.3 in /home/7/21D30114/.local/lib/python3.7/site-packages (from pandas->ray[rllib]==2.3) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /home/7/21D30114/.local/lib/python3.7/site-packages (from pandas->ray[rllib]==2.3) (2022.7.1)
Requirement already satisfied: idna<4,>=2.5 in /home/7/21D30114/.local/lib/python3.7/site-packages (from requests->ray[rllib]==2.3) (3.4)
Requirement already satisfied: certifi>=2017.4.17 in /home/7/21D30114/anaconda3/envs/pydrone37/lib/python3.7/site-packages (from requests->ray[rllib]==2.3) (2022.12.7)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/7/21D30114/.local/lib/python3.7/site-packages (from requests->ray[rllib]==2.3) (1.26.15)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/7/21D30114/.local/lib/python3.7/site-packages (from requests->ray[rllib]==2.3) (3.1.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /home/7/21D30114/.local/lib/python3.7/site-packages (from rich->ray[rllib]==2.3) (2.14.0)
Requirement already satisfied: markdown-it-py<3.0.0,>=2.2.0 in /home/7/21D30114/.local/lib/python3.7/site-packages (from rich->ray[rllib]==2.3) (2.2.0)
Requirement already satisfied: pillow!=7.1.0,!=7.1.1,!=8.3.0,>=6.1.0 in /home/7/21D30114/.local/lib/python3.7/site-packages (from scikit-image->ray[rllib]==2.3) (9.4.0)
Requirement already satisfied: tifffile>=2019.7.26 in /home/7/21D30114/.local/lib/python3.7/site-packages (from scikit-image->ray[rllib]==2.3) (2021.11.2)
Requirement already satisfied: imageio>=2.4.1 in /home/7/21D30114/.local/lib/python3.7/site-packages (from scikit-image->ray[rllib]==2.3) (2.26.0)
Requirement already satisfied: networkx>=2.2 in /home/7/21D30114/.local/lib/python3.7/site-packages (from scikit-image->ray[rllib]==2.3) (2.6.3)
Requirement already satisfied: PyWavelets>=1.1.1 in /home/7/21D30114/.local/lib/python3.7/site-packages (from scikit-image->ray[rllib]==2.3) (1.3.0)
Requirement already satisfied: zipp>=0.5 in /home/7/21D30114/.local/lib/python3.7/site-packages (from importlib-metadata>=4.8.0->gymnasium==0.26.3->ray[rllib]==2.3) (3.15.0)
Requirement already satisfied: mdurl~=0.1 in /home/7/21D30114/.local/lib/python3.7/site-packages (from markdown-it-py<3.0.0,>=2.2.0->rich->ray[rllib]==2.3) (0.1.2)
Requirement already satisfied: six>=1.5 in /home/7/21D30114/.local/lib/python3.7/site-packages (from python-dateutil>=2.7.3->pandas->ray[rllib]==2.3) (1.16.0)
/home/7/21D30114/anaconda3/envs/pydrone37/bin/python3: No module named HOROVOD_GPU_ALLREDUCE=NCCL
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu113
Requirement already satisfied: torch==1.12.1+cu113 in /home/7/21D30114/.local/lib/python3.7/site-packages (1.12.1+cu113)
Requirement already satisfied: torchvision==0.13.1+cu113 in /home/7/21D30114/.local/lib/python3.7/site-packages (0.13.1+cu113)
Requirement already satisfied: torchaudio==0.12.1 in /home/7/21D30114/.local/lib/python3.7/site-packages (0.12.1+cu113)
Requirement already satisfied: typing-extensions in /home/7/21D30114/.local/lib/python3.7/site-packages (from torch==1.12.1+cu113) (4.5.0)
Requirement already satisfied: requests in /home/7/21D30114/.local/lib/python3.7/site-packages (from torchvision==0.13.1+cu113) (2.28.2)
Requirement already satisfied: numpy in /home/7/21D30114/.local/lib/python3.7/site-packages (from torchvision==0.13.1+cu113) (1.21.6)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in /home/7/21D30114/.local/lib/python3.7/site-packages (from torchvision==0.13.1+cu113) (9.4.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/7/21D30114/.local/lib/python3.7/site-packages (from requests->torchvision==0.13.1+cu113) (1.26.15)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/7/21D30114/.local/lib/python3.7/site-packages (from requests->torchvision==0.13.1+cu113) (3.1.0)
Requirement already satisfied: certifi>=2017.4.17 in /home/7/21D30114/anaconda3/envs/pydrone37/lib/python3.7/site-packages (from requests->torchvision==0.13.1+cu113) (2022.12.7)
Requirement already satisfied: idna<4,>=2.5 in /home/7/21D30114/.local/lib/python3.7/site-packages (from requests->torchvision==0.13.1+cu113) (3.4)
pybullet build time: May 20 2022 19:43:01
2023-03-17 01:31:27,028	INFO worker.py:1553 -- Started a local Ray instance.
/home/7/21D30114/.local/lib/python3.7/site-packages/gym/spaces/box.py:127: UserWarning: [33mWARN: Box bound precision lowered by casting to float32[0m
  logger.warn(f"Box bound precision lowered by casting to {self.dtype}")
[2m[36m(PPO pid=41484)[0m 2023-03-17 01:31:37,075	WARNING algorithm_config.py:597 -- Cannot create PPOConfig from given `config_dict`! Property __stdout_file__ not supported.
[2m[36m(PPO pid=41484)[0m pybullet build time: May 20 2022 19:43:01
[2m[36m(PPO pid=41484)[0m 2023-03-17 01:31:37,710	INFO algorithm.py:507 -- Current log_level is WARN. For more information, set 'log_level': 'INFO' / 'DEBUG' or use the -v and -vv flags.
[2m[36m(PPO pid=41484)[0m /home/7/21D30114/.local/lib/python3.7/site-packages/gym/spaces/box.py:127: UserWarning: [33mWARN: Box bound precision lowered by casting to float32[0m
[2m[36m(PPO pid=41484)[0m   logger.warn(f"Box bound precision lowered by casting to {self.dtype}")
[2m[36m(PPO pid=41484)[0m 2023-03-17 01:31:37,918	WARNING env.py:297 -- Your MultiAgentEnv <LeaderFollowerAviary instance> does not have some or all of the needed base-class attributes! Make sure you call `super().__init__()` from within your MutiAgentEnv's constructor. This will raise an error in the future.
2023-03-17 01:31:38,327	ERROR trial_runner.py:1062 -- Trial PPO_this-aviary-v0_03ed4_00000: Error processing event.
ray.exceptions.RayTaskError(TypeError): [36mray::PPO.train()[39m (pid=41484, ip=10.0.0.221, repr=PPO)
  File "/home/7/21D30114/.local/lib/python3.7/site-packages/ray/tune/trainable/trainable.py", line 368, in train
    raise skipped from exception_cause(skipped)
  File "/home/7/21D30114/.local/lib/python3.7/site-packages/ray/tune/trainable/trainable.py", line 365, in train
    result = self.step()
  File "/home/7/21D30114/.local/lib/python3.7/site-packages/ray/rllib/algorithms/algorithm.py", line 782, in step
    results, train_iter_ctx = self._run_one_training_iteration()
  File "/home/7/21D30114/.local/lib/python3.7/site-packages/ray/rllib/algorithms/algorithm.py", line 2713, in _run_one_training_iteration
    results = self.training_step()
  File "/home/7/21D30114/.local/lib/python3.7/site-packages/ray/rllib/algorithms/ppo/ppo.py", line 359, in training_step
    worker_set=self.workers, max_env_steps=self.config.train_batch_size
  File "/home/7/21D30114/.local/lib/python3.7/site-packages/ray/rllib/execution/rollout_ops.py", line 82, in synchronous_parallel_sample
    sample_batches = [worker_set.local_worker().sample()]
  File "/home/7/21D30114/.local/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py", line 914, in sample
    batches = [self.input_reader.next()]
  File "/home/7/21D30114/.local/lib/python3.7/site-packages/ray/rllib/evaluation/sampler.py", line 92, in next
    batches = [self.get_data()]
  File "/home/7/21D30114/.local/lib/python3.7/site-packages/ray/rllib/evaluation/sampler.py", line 277, in get_data
    item = next(self._env_runner)
  File "/home/7/21D30114/.local/lib/python3.7/site-packages/ray/rllib/evaluation/env_runner_v2.py", line 323, in run
    outputs = self.step()
  File "/home/7/21D30114/.local/lib/python3.7/site-packages/ray/rllib/evaluation/env_runner_v2.py", line 342, in step
    ) = self._base_env.poll()
  File "/home/7/21D30114/.local/lib/python3.7/site-packages/ray/rllib/env/multi_agent_env.py", line 633, in poll
    ) = env_state.poll()
  File "/home/7/21D30114/.local/lib/python3.7/site-packages/ray/rllib/env/multi_agent_env.py", line 825, in poll
    self.reset()
  File "/home/7/21D30114/.local/lib/python3.7/site-packages/ray/rllib/env/multi_agent_env.py", line 909, in reset
    raise e
  File "/home/7/21D30114/.local/lib/python3.7/site-packages/ray/rllib/env/multi_agent_env.py", line 903, in reset
    obs_and_infos = self.env.reset(seed=seed, options=options)
TypeError: reset() got an unexpected keyword argument 'seed'
[2m[36m(PPO pid=41484)[0m 2023-03-17 01:31:38,307	WARNING util.py:67 -- Install gputil for GPU system monitoring.
[INFO] BaseAviary.__init__() loaded parameters from the drone's .urdf:
[INFO] m 0.027000, L 0.039700,
[INFO] ixx 0.000014, iyy 0.000014, izz 0.000022,
[INFO] kf 0.000000, km 0.000000,
[INFO] t2w 2.250000, max_speed_kmh 30.000000,
[INFO] gnd_eff_coeff 11.368590, prop_radius 0.023135,
[INFO] drag_xy_coeff 0.000001, drag_z_coeff 0.000001,
[INFO] dw_coeff_1 2267.180000, dw_coeff_2 0.160000, dw_coeff_3 -0.110000
[2m[36m(PPO pid=41484)[0m [INFO] BaseAviary.__init__() loaded parameters from the drone's .urdf:
[2m[36m(PPO pid=41484)[0m [INFO] m 0.027000, L 0.039700,
[2m[36m(PPO pid=41484)[0m [INFO] ixx 0.000014, iyy 0.000014, izz 0.000022,
[2m[36m(PPO pid=41484)[0m [INFO] kf 0.000000, km 0.000000,
[2m[36m(PPO pid=41484)[0m [INFO] t2w 2.250000, max_speed_kmh 30.000000,
[2m[36m(PPO pid=41484)[0m [INFO] gnd_eff_coeff 11.368590, prop_radius 0.023135,
[2m[36m(PPO pid=41484)[0m [INFO] drag_xy_coeff 0.000001, drag_z_coeff 0.000001,
[2m[36m(PPO pid=41484)[0m [INFO] dw_coeff_1 2267.180000, dw_coeff_2 0.160000, dw_coeff_3 -0.110000
== Status ==
Current time: 2023-03-17 01:31:38 (running for 00:00:03.96)
Memory usage on this node: 54.1/251.3 GiB 
Using FIFO scheduling algorithm.
Resources requested: 1.0/56 CPUs, 0/4 GPUs, 0.0/158.04 GiB heap, 0.0/71.72 GiB objects (0.0/1.0 accelerator_type:P100)
Result logdir: /gs/hs0/tga-aklab/pybullet_paehal_ray23/gym-pybullet-drones-ray23/experiments/learning/results/save-leaderfollower-2-cc-kin-dyn-03.17.2023_01.31.24/PPO
Number of trials: 1/1 (1 RUNNING)


== Status ==
Current time: 2023-03-17 01:31:38 (running for 00:00:04.09)
Memory usage on this node: 54.1/251.3 GiB 
Using FIFO scheduling algorithm.
Resources requested: 0/56 CPUs, 0/4 GPUs, 0.0/158.04 GiB heap, 0.0/71.72 GiB objects (0.0/1.0 accelerator_type:P100)
Result logdir: /gs/hs0/tga-aklab/pybullet_paehal_ray23/gym-pybullet-drones-ray23/experiments/learning/results/save-leaderfollower-2-cc-kin-dyn-03.17.2023_01.31.24/PPO
Number of trials: 1/1 (1 ERROR)
Number of errored trials: 1
+--------------------------------+--------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Trial name                     |   # failures | error file                                                                                                                                                                                                             |
|--------------------------------+--------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| PPO_this-aviary-v0_03ed4_00000 |            1 | /gs/hs0/tga-aklab/pybullet_paehal_ray23/gym-pybullet-drones-ray23/experiments/learning/results/save-leaderfollower-2-cc-kin-dyn-03.17.2023_01.31.24/PPO/PPO_this-aviary-v0_03ed4_00000_0_2023-03-17_01-31-34/error.txt |
+--------------------------------+--------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

Traceback (most recent call last):
  File "experiments/learning/multiagent.py", line 295, in <module>
    local_dir=filename,
  File "/home/7/21D30114/.local/lib/python3.7/site-packages/ray/tune/tune.py", line 792, in run
    raise TuneError("Trials did not complete", incomplete_trials)
ray.tune.error.TuneError: ('Trials did not complete', [PPO_this-aviary-v0_03ed4_00000])
